### PR TITLE
Progress bar seek renders faster and before rest of app.

### LINKED ISSUE #385: ProgressBar seek feels slow

### PR DESCRIPTION
**Pull request by benwiley4000**
Closes #385.

### CODE REVIEW

**Comment by danielr18** [comment]
Was there a breaking change here? Seeking is broken in my app on alpha 29

**Comment by benwiley4000** [comment]
Not intentionally!

**Comment by benwiley4000** [comment]
@danielr18 can you provide any more info on how exactly it's broken? It's working for me in all the examples.

**Comment by danielr18** [comment]
When I seek to any position, the currentTime resets to 0

**Comment by danielr18** [comment]
```javascript
import React from 'react'
import classNames from 'classnames'
import { ProgressBar } from '@cassette/components'
import Handle from './Handle'
import * as styles from './styles'

class SeekBar extends React.PureComponent {
  handleSeekPreview = progress => {
    this.props.onSeekPreview(progress * this.props.duration)
  }

  render() {
    const { duration, currentTime, onSeekComplete } = this.props
    const displayedProgress = duration ? currentTime / duration : 0

    return (
      <div className={this.props.className}>
        <ProgressBar
          className={classNames('progressbar', styles.progressbar.className)}
          progressClassName={classNames('progress', styles.progressbar.className)}
          progress={displayedProgress}
          progressDirection="right"
          readonly={false}
          onAdjustProgress={this.handleSeekPreview}
          onAdjustComplete={onSeekComplete}
          handle={<Handle />}
        />
        {styles.progressbar.styles}
      </div>
    )
  }
}

export default SeekBar
```

**Comment by danielr18** [comment]
When I seek to any position, onAdjustComplete is called with a time like: 0.8875

**Comment by benwiley4000** [comment]
Ah yes... I didn't intend this as a breaking change but I see how it was. I added a new `handleSeekComplete` to the `MediaProgressBar` component to deal with the change.

https://github.com/benwiley4000/cassette/blob/next/packages/components/src/MediaProgressBar.js#L28

Does this seem ok? I'll update the release notes to mark this as a breaking change.

**Comment by benwiley4000** [comment]
The reason I did this is because now the `onAdjustProgress` callback gets called after component update and I wanted to make sure the latest progress value does get sent in case the last `handleAdjustProgress` and `handleAdjustComplete` updates get batched.

**Comment by danielr18** [comment]
It works now, missed that.

**Comment by benwiley4000** [comment]
That's my fault.. thanks for reporting it!

**Pull request merged**
